removed server variables
OpenLiberty/guide-microprofile-openapi pull request #105
Opened 2020-10-28 18:18 UTC by tt-le

Since `mpOpenAPI 1.1` `ServerVariables` are deprecated.

2020-10-29 15:59 UTC, AustinSeto approved these changes
Tested from `finish` directory, no more warning, LGTM

2020-10-29 20:29 UTC, arturdzm approved these changes

2020-11-03 16:16 UTC, gkwan-ibm requested changes

2020-11-03 16:26 UTC, tt-le commented on finish/src/main/java/io/openliberty/guides/inventory/filter/InventoryOASFilter.java
> +    openAPI.addServer(OASFactory.createServer()
Just now changed the formatting.

2020-11-03 16:49 UTC, gkwan-ibm approved these changes

2020-11-05 17:34 UTC, merged